version: '3'
services:
 http-go:
   container_name: http-go
   build: ./app
   ports:
    - "9090:9090"
   expose:
    - "9090"
   links:
    - redis
   environment:
    - REDIS_URL=redis:6379

 redis:
  container_name: redis
  image: redis
  expose:
    - "6379"
