apiVersion: v1
kind: Service
metadata:
  name: http-go
  labels:
    app: http-go
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app: http-go
    tier: frontend
