apiVersion: v1
kind: Service
metadata:
  name: http-go
  labels:
    app: http-go
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: http-go
    tier: frontend
  ports:
  - protocol: TCP        
    port: 9090
